version: "3"
services:
  postgresql-server:
    container_name: postgresql-server
    image: postgres:10.5
    ports:
      - 5432:5432
    volumes:
      - /root/containers/postgresql/postgresql-datadir:/var/lib/postgresql/data
    env_file:
      - .env
